### ISSUE TITLE
Add videos from Dnepr.py #4

### ISSUE THREAD

**Issue by gleb-petrov-1986** [coagulant/pyvideo.ru#27]
text
http://www.meetup.com/uapycon/events/221861247/

playlist
https://www.youtube.com/playlist?list=PLyUvGavKi98XcJpJPvO2EJ7DVY7nNZpMg

**Comment by coagulant** [comment]
Thanks for the link!

If anyone got time for it, one can add new videos via pull request. There are already [examples in closed pull-requests](https://github.com/coagulant/pyvideo.ru/pulls?q=is%3Apr+is%3Aclosed+label%3Aproposal). Detailed instructions are in [contributing guidelines](https://github.com/coagulant/pyvideo.ru/blob/master/CONTRIBUTING.rst).

**Comment by sasha-medve** [comment]
Эти видео добавили, тикет, наверное, нужно закрыть.
