### ISSUE TITLE
Не работает поиск по строке

### ISSUE THREAD

**Issue by sasha-medve** [coagulant/pyvideo.ru#28]
01 Заходим на http://pyvideo.ru/

02 Видим в разделе "Последние видеозаписи" видео "Документирование и тестирование HTTP API с помощью Sphinx"

03 Вводим в поиск "Sphinx"

04 Результат поиска "Ничего не найдено "
http://pyvideo.ru/search?models=videos.video&q=Sphinx

В моём понимании должно находить как минимум 1 видео "Документирование и тестирование HTTP API с помощью Sphinx"

**Comment by coagulant** [comment]
Посмотрю, скорее всего проблема elasticsearch. Спасибо

**Comment by coagulant** [comment]
Починено
