### ISSUE TITLE
Не работает поиск по тегу

### ISSUE THREAD

**Issue by sasha-medve** [coagulant/pyvideo.ru#29]
01 Заходим на http://pyvideo.ru/

02 Видим тег "API" в нижней центральной части страницы

03 Нажимаем на тег "API"

04 Результат поиска "Ничего не найдено"
http://pyvideo.ru/search/?tag=api

В моём понимании должно находить как минимум 1 видео "Документирование и тестирование HTTP API с помощью Sphinx"

**Comment by coagulant** [comment]
#28 дубликат
