### ISSUE TITLE
Проект заглох?

### ISSUE THREAD

**Issue by sasha-medve** [coagulant/pyvideo.ru#30]
Довольно давно не появлялось обновлений 
(например с https://www.youtube.com/user/moscowdjangoru/videos).

Проект заглох?

**Comment by coagulant** [comment]
Саша, есть желание помочь?

**Comment by sasha-medve** [comment]
Могу выделить 1-2 часа в неделю.
А как именно можно помочь?

**Comment by coagulant** [comment]
Новые видео можно добавлять через пул-реквесты, вот инструкция https://github.com/coagulant/pyvideo.ru/blob/master/CONTRIBUTING.rst
Если хочется помочь проекту, будет здорово

**Comment by sasha-medve** [comment]
А  нет какого-то списка новых видео, которые уже доступны, но ещё не добавлены в проект?

**Comment by coagulant** [comment]
Из того, что я помню #27

**Comment by coagulant** [comment]
Можно ещё с moscowdjango.ru добавить.
