### ISSUE TITLE
Несколько ссылок на одного автора

### ISSUE THREAD

**Issue by sasha-medve** [coagulant/pyvideo.ru#39]
Нашел несколько ссылок на одного и того же автора

Максим Климишин - http://pyvideo.ru/speaker/48/maksim-klimishin

Maksym Klymyshyn - http://pyvideo.ru/speaker/164/maksym-klymyshyn

Было бы хорошо объединить.

**Comment by coagulant** [comment]
Остался только один http://pyvideo.ru/speaker/48/maksim-klimishin

**Comment by sasha-medve** [comment]
> Остался только один

Похоже, что их все ещё 2.

По ссылке http://pyvideo.ru/category/17/kyivpy
видим 2 одинаковых доклада 'Django without Django'.

И можно нажать на автора
http://pyvideo.ru/speaker/48/maksim-klimishin (Number of videos: 3)
http://pyvideo.ru/speaker/190/maksym-klymyshyn (Number of videos: 2)

**Comment by coagulant** [comment]
Ага, после #38 добавился новый :) Уберу
