### ISSUE TITLE
yandex | Python party 2 сентября 2015

### ISSUE THREAD

**Issue by sasha-medve** [coagulant/pyvideo.ru#43]
Появились новые видео
https://events.yandex.ru/events/meetings/02-september-2015/

Можно их как-то добавить?
Спрашиваю, т.к. источник видео не на youtube.

**Comment by coagulant** [comment]
По-моему должно работать, т.к. внутри мы их встраиваем через http://embed.ly/
Предлагаю попробовать с одним видео, если тесты пройдут добавить остальные

**Comment by sasha-medve** [comment]
Что-то у меня ничего не изменилось на http://pyvideo.ru/ после merge...

**Comment by coagulant** [comment]
Странно, что-то отвалилось с авторизацией при деплое, буду разбираться https://travis-ci.org/coagulant/pyvideo.ru/builds/80588896#L571

**Comment by coagulant** [comment]
Видео появилось, но без данных, видимо придётся руками вкручивать, либо обновлять review-скрипт
